### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by EMGXF** [Shevchik/AnimatedPing#1]
So this is a plugin, right?
Not an API?

**Comment by EMGXF** [comment]
Ok thanks.
How can I compile this?

**Comment by MaRoTheTroLLeR** [comment]
sith Eclilse :D

**Comment by EMGXF** [comment]
@MaRoTheTroLLeR Well I have Eclipse, I just don't know the steps for compiling. I believe I have to import first, correct?

**Comment by MaRoTheTroLLeR** [comment]
@EMGXF  then click add external jars and add Spigot 1.8 and Protocollib and when you are ready export it as a jar file.

**Comment by EMGXF** [comment]
@MaRoTheTroLLeR Thanks but it doesn't show the option for adding external JARs in build path
http://imgur.com/iObfZ4L

**Comment by MaRoTheTroLLeR** [comment]
@EMGXF is this java project ? because i don't think so

**Comment by EMGXF** [comment]
Here's my steps
File, Import, Projects from Git, Clone URI (filled out the URI field), Next button, Select Master, Next button, Import as general project, Next button, Finish.
Did I do it correctly?
@MaRoTheTroLLeR

**Comment by EMGXF** [comment]
OH WAIT I just realized my import isn't a java project.
How do I turn an import into a java project??

**Comment by Shevchik** [comment]
You need to reimport it as java project. You also need bukkit and protocol lib in your project->build path.

**Comment by EMGXF** [comment]
@Shevchik My server uses Spigot 1.8..is that fine?
Also, I use the new 1.8 PLib right? 
http://assets.comphenix.net/job/ProtocolLib/

**Comment by Shevchik** [comment]
Yep

**Comment by EMGXF** [comment]
Ok I apologize but one last thing, what do you mean by import as java project?
Is that same as clone URI?
Or do I have to export the clone as an archive file, and import that?

**Comment by EMGXF** [comment]
:0 sorry I'm dumb

**Comment by MaRoTheTroLLeR** [comment]
you can just create java project and drag and drop the files in it :D

**Comment by EMGXF** [comment]
That gives a bunch of errors and pastes something called snippet..?
I'd rather do it the correct way that you're supposed to.
This is about more than this plugin, I want to learn how to do with any repo

**Comment by EMGXF** [comment]
I'd rather do it the correct way, this is about more than just this plugin, I want to learn how to do it with any repo.

**Comment by EMGXF** [comment]
@Shevchik Ok I tried something and got 11KB..is this correct?

**Comment by MaRoTheTroLLeR** [comment]
@EMGXF yep

**Comment by EMGXF** [comment]
yeeeeeeeeeeeESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
I imported the source, exported as an archive, created a java project, imported the archive, copied it over to the java project, added libs, and exported as a jar.

**Comment by MaRoTheTroLLeR** [comment]
nice

**Comment by EMGXF** [comment]
Shoot.
Plugin not loading, no error log.

**Comment by EMGXF** [comment]
Hi @Shevchik Can you help?
